# Generated by Django 5.2.4 on 2025-09-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_appliedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='No description provided', null=True),
        ),
    ]
