# Generated by Django 5.2.4 on 2025-09-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
