# Generated by Django 5.2.4 on 2025-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
