# Generated by Django 5.2.4 on 2025-09-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, default='Not specified', max_length=255, null=True),
        ),
    ]
